Completion: use the new GtkSourceCompletionItem API
GtkSourceView 3.24 is not yet released, git master is needed. But Vala
doesn't like that, it triggers the following error:

error: Gtk.SourceCompletionItem.new2 is not available in
gtksourceview-3.0 3.23.1. Use gtksourceview-3.0 >= 3.24

So add temporarily the --disable-since-check valac flag. Thanks, Vala.